### ISSUE TITLE
Graphique p1.q1.data

### ISSUE THREAD

**Issue by emeric254** [emeric254/qnap-STRI#4]
Voir pour condition pour convertir graph 3d en 2d avec de multiple courbes

**Comment by Gui-B** [comment]
plot "calcul.p1.q1.data" u 1:( $2 ==10 ? $3 : 1/0) w l t "Taux de rejet pour de 10", \
 "calcul.p1.q1.data" u 1:( $2 ==20 ? $3 : 1/0) w l  t "taux pour 20", \
 "calcul.p1.q1.data" u 1:( $2 ==30 ? $3 : 1/0) w l  t "taux pour 30", \
 "calcul.p1.q1.data" u 1:( $2 ==40 ? $3 : 1/0) w l  t "taux pour 40", \
 "calcul.p1.q1.data" u 1:( $2 ==50 ? $3 : 1/0) w l  t "taux pour 50", \
 "calcul.p1.q1.data" u 1:( $2 ==50 ? $3 : 1/0) w l  t "taux pour 50", \
 "calcul.p1.q1.data" u 1:( $2 ==60 ? $3 : 1/0) w l  t "taux pour 60", \
 "calcul.p1.q1.data" u 1:( $2 ==70 ? $3 : 1/0) w l  t "taux pour 70", \
 "calcul.p1.q1.data" u 1:( $2 ==80 ? $3 : 1/0) w l  t "taux pour 80"
