### ISSUE TITLE
Graphique p1.q2.data

### ISSUE THREAD

**Issue by emeric254** [emeric254/qnap-STRI#5]
Voir pour condition pour convertir graph 3d en 2d avec de multiple courbes.

**Comment by Gui-B** [comment]
plot "p1.q2.data" u 2:( $1 ==10 ? $5 : 1/0) w l t "Taux de rejet pour de 10", \
 "p1.q2.data" u 2:( $1 ==20 ? $5 : 1/0) w l  t "taux pour 20", \
 "p1.q2.data" u 2:( $1 ==30 ? $5 : 1/0) w l  t "taux pour 30", \
 "p1.q2.data" u 2:( $1 ==40 ? $5 : 1/0) w l  t "taux pour 40", \
 "p1.q2.data" u 2:( $1 ==50 ? $5 : 1/0) w l  t "taux pour 50", \
 "p1.q2.data" u 2:( $1 ==50 ? $5 : 1/0) w l  t "taux pour 50", \
 "p1.q2.data" u 2:( $1 ==60 ? $5 : 1/0) w l  t "taux pour 60", \
 "p1.q2.data" u 2:( $1 ==70 ? $5 : 1/0) w l  t "taux pour 70", \
 "p1.q2.data" u 2:( $1 ==80 ? $5 : 1/0) w l  t "taux pour 80"
